config/routes.rb
Pms::Application.routes.draw do
  get "sessions/new"
  get 'login', to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :servers
  resources :services
  resources :categories
  resources :devices
  resources :sessions

  root :to => 'home#index'

  scope "/:locale" do
    resources :homes, :only => [:index]
    resources :devices, :only => [ :index, :show, :edit, :update ]
    resources :servers, :only => [ :index, :show, :edit, :update ]
    resources :services, :only => [ :index, :show, :edit, :update ]
    resources :categories, :only => [:index, :show, :edit, :update]
  end

end

app/models/server.rb
class Server < ActiveRecord::Base
  belongs_to :device
  belongs_to :category
  belongs_to :service
  attr_accessible :ip, :name, :password, :port, :root_password, :sysadm, :user, :device_id, :category_id, :service_id
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  #before_filter :authorize
  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @devices       = Device.all
    @categories    = Category.all
    @services      = Service.all

    @device   = Device.new
    @server   = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render json: @server, status: :created, location: @server }
      else
        format.html { render action: "new" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<script type="text/javascript">
  function deviceModal(){
    $('#deviceModal').modal('show');
    $('#categoryModal').modal('show');
  }  
</script>

<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device %><br />
    <%= f.select :device_id, @devices.collect{|d| [d.name, d.id]} %>
    <%= link_to_modal 'Add Device', new_device_path, :width=> "600", :height =>"400", :remote => true %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category_id, @categories.collect{|t| [t.name, t.id]} %>
    <%= link_to_modal 'Add Category', new_category_path, :width=> "600", :height =>"400", :remote => true %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :service %><br />
    <%= f.select :service_id, @services.collect{|s| [s.name, s.id]} %>
    <%= link_to_modal 'Add Service', new_service_path, :width=> "600", :height =>"400", :remote => true %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.text_field :port %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :sysadm %><br />
    <%= f.check_box :sysadm %>
  </div>
  <div class="field">
    <%= f.label :root_password %><br />
    <%= f.text_field :root_password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing Servers</h1>

<table class="table table-striped">
  <tr>
    <th>Device</th>
    <th>Type</th>
    <th>Name</th>
    <th>Ip</th>
    <th>Service</th>
    <th>Port</th>
    <th>User</th>
    <th>Password</th>
    <th>Sysadm</th>
    <th>Password Root</th>
    
    
    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servers.each do |server| %>
  <tr>
    <td><%= server.device.name %></td>
    <td><%= server.type.name %></td>
    <td><%= server.name %></td>
    <td><%= server.ip %></td>
    <td><%= server.service.name %></td>
    <td><%= server.port %></td>
    <td><%= server.user %></td>
    <td><%= server.password %></td>
    <td><%= server.sysadm ? "SIM" : "NÃO"%></td>
    <td><%= server.root_password %></td>
    
    
   
    <td><%= link_to 'Show', server %></td>
    <td><%= link_to 'Edit', edit_server_path(server) %></td>
    <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= button_to 'New Server', new_server_path, :class => "btn  btn-primary", :method => :get %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @server.name %>
</p>

<p>
  <b>Ip:</b>
  <%= @server.ip %>
</p>

<p>
  <b>Port:</b>
  <%= @server.port %>
</p>

<p>
  <b>User:</b>
  <%= @server.user %>
</p>

<p>
  <b>Password:</b>
  <%= @server.password %>
</p>

<p>
  <b>Sysadm:</b>
  <%= @server.sysadm %>
</p>

<p>
  <b>Root password:</b>
  <%= @server.root_password %>
</p>

<p>
  <b>Device:</b>
  <%= @server.device %>
</p>

<p>
  <b>Type:</b>
  <%= @server.type %>
</p>

<p>
  <b>Service:</b>
  <%= @server.service %>
</p>


<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>