config/routes.rb
Pms::Application.routes.draw do
  get "sessions/new"
  get 'login', to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :servers
  resources :services
  resources :categories
  resources :devices
  resources :sessions

  root :to => 'home#index'

  scope "/:locale" do
    resources :homes, :only => [:index]
    resources :devices, :only => [ :index, :show, :edit, :update ]
    resources :servers, :only => [ :index, :show, :edit, :update ]
    resources :services, :only => [ :index, :show, :edit, :update ]
    resources :categories, :only => [:index, :show, :edit, :update]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>PMS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="PMS - Password Manager System, sistema de gerênciamento de senhas para servidor">
  <meta name="author" content="Régis Eduardo Weizenmann Gregol (regiseduardogregol@gmail.com)">
  <link rel="shortcut icon" href="/favicon.png">
  <%= stylesheet_link_tag "application", "bootstrap", "bootstrap.min", "bootstrap-responsive", "font-awesome.min", "font-awesome", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
	   <div class="container">
	    	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
          	</a>
	        <%= link_to "PMS", root_path, :class => "brand icon-key" %>
	        <div class="nav-collapse collapse">
	        	<ul class="nav">
					<li class="<%= 'active' if params[:controller] == 'home' %>"><%= link_to "Home", root_path %></li>
					<li class="<%= 'active' if params[:controller] == 'devices' %>"><%= link_to "Devices", devices_path %></li>
					<li class="<%= 'active' if params[:controller] == 'services' %>"><%= link_to "Services", services_path %></li>
					<li class="<%= 'active' if params[:controller] == 'categories' %>"><%= link_to "Categories", categories_path %></li>
				</ul>
	        </div>
       </div>
    </div>
</div>
	<div class="container">
		<%= yield %>
	</div>
	<div class="container">
		<hr>
		<footer>
		    <p>&copy; Password Manager System — 2013</p>
		</footer>
	</div>
		<%= javascript_include_tag "application", "bootstrap", "jquery-ui" %>
	</body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Log in - Estoque ITAI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <style type="text/css">
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        /*padding-top: 40px;*/
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

      #footer {
        text-align: center;
      }

      .navbar .container {
        font-family: "Helvetica";
        text-align: center;
        line-height: 45px;
        font-size: 23px;
      }

    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-fixed-top navbar-inner">
      <div class="container">
        PMS<strong> Password Management System</strong> <span class="label label-inverse">v1.0</span>
      </div>
    </div>

    <div class="container">
      <%= form_tag sessions_path, class: "form-signin" do %>
        <h2 class="form-signin-heading">Login</h2>
        <% if flash[:notice] %>
          <div class="alert alert-error">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%= text_field_tag "username", nil, class: "input-block-level", placeholder: "Usuário" %>
        <%= password_field_tag "password", nil, class: "input-block-level", placeholder: "Senha" %>
        <%= submit_tag "Entrar", class: "btn btn-large btn-primary" %>
      <% end %>

    </div> <!-- /container -->

    <div id="footer">
      <!--<p><%#= image_tag "itai2.png", alt: "ITAI" %></p>-->
    </div>
  </body>
</html>